version: '3'
services:
  zabbix-db:
    image: monitoringartist/zabbix-db-mariadb
    container_name: zabbix-db
    hostname: zabbix-db
    restart: always
    volumes:
      - zabbix-db-storage:/var/lib/mysql
      - backups:/backups
      - /etc/localtime:/etc/localtime:ro
    environment:
      - MARIADB_USER=zabbix
      - MARIADB_PASS=zabbix
  zabbix-server:
    image: monitoringartist/zabbix-xxl
    container_name: zabbix-server
    hostname: zabbix-server
    restart: always

    ports:
      - "80:80"
      - "10051:10051"
    volumes:
      - /etc/localtime:/etc/localtime:ro
    links:
      - zabbix-db:zabbix.db
    environment:
      - ZS_DBHost=zabbix.db
      - ZS_DBUser=zabbix
      - ZS_DBPassword=zabbix
volumes:
  zabbix-db-storage:
    driver: local
  backups:
    driver: local
