version: '2'
services:
  zabbix-server:
    image: ${REGISTRY_HOST}:5000/zabbix-server:${ZABBIX_SERVER_IMAGE_VERSION}
    container_name: zabbix_server
    ports:
      - "10051:10051"
    environment:
      - "ZS_DBUser=${ZS_DBUser}"
      - "ZS_DBPassword=${ZS_DBPassword}"
      - "constraint:node==${NODE}" # Temporaly hardcoded
      - "HOST_PRIVATE_IP=${ZBX_HOST_PRIVATE_IP}"
      - "ETCD_HOST=${ETCD_HOST}"
      - "IPNETCOM_DOMAINNAME=${IPNETCOM_DOMAINNAME}"
      - 'PROXY_MW_NETWORK_NAME=proxies_middleware'
      - 'ZA_UnsafeUserParameters=1'
      - 'ZA_UserParameter_1=containers.up[*],/count_swarm_containers.sh $$1'
      - 'ZA_UserParameter_2=pxc.discovery[*],/pxc_discovery.sh'
      - 'ZA_UserParameter_3=percona.pxc_status[*],/percona_status_query.sh $$1 $$2'
    networks:
      - proxies_middleware
      - databases_database
    restart: always
    logging:
      driver: gelf
      options:
        gelf-address: "udp://${LOGGING_HOST}"
  zabbix-agent:
    image: ${REGISTRY_HOST}:5000/zabbix-agent:${ZABBIX_AGENT_IMAGE_VERSION}
    restart: always
    privileged : true
    ports:
      - "10050:10050"
    volumes:
      - /:/rootfs:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/hostname:/hostname:ro
     # - /data/zabbix/modules:/var/lib/zabbix/modules
    environment:
      - "ZBX_ENABLEREMOTECOMMANDS=1"
      - "ZBX_DEBUGLEVEL=3"
      - "ZBX_LOADMODULE=zabbix_module_docker.so"
      - "affinity:container!=*zabbix-agent*"
      - "ETCD_HOST=${ETCD_HOST_WITHOUT_PORT}:${ETCD_PROXY_PORT}"
#      - "ZBX_SERVER_HOST=${ZBX_HOST_PRIVATE_IP}"
#    networks:
#      - middleware_middleware
    network_mode: "host"
    extra_hosts:
      - "${ETCD_HOST_WITHOUT_PORT}:127.0.0.1"
    logging:
      driver: gelf
      options:
        gelf-address: "udp://${LOGGING_HOST}"
    depends_on:
      - zabbix-server
      - etcd-proxy
  etcd-proxy:
    image: istepanov/socat
    command: "TCP4-LISTEN:80,fork TCP4:${ETCD_HOST}"
    restart: always
    environment:
      - "affinity:container!=*etcd-proxy*"
    networks:
      - proxies_middleware
    ports:
      - "${ETCD_PROXY_PORT}:80"
    depends_on:
      - zabbix-server

networks:
  databases_database:
    external: true
  proxies_middleware:
    external: true
